workers_dev = true
name = "my-worker"
compatibility_date = "2024-11-18"
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[[durable_objects.bindings]]
name = "WEBSOCKET_MANAGER"
class_name = "WebSocketManager"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketManager"]