import { readFile, rm } from "node:fs/promises";
import path from "node:path";
import { afterEach, expect, test } from "vitest";
import { type FixtureApp, ProductionFixture } from "../helpers/fixture";
import { fixtureBin, runCommand } from "../helpers/process";

let app: FixtureApp | undefined;

function serverSource(adapter: string) {
  return `// generated by react-router-hono-server/dev
import { createHonoServer } from "react-router-hono-server/${adapter}";

export default await createHonoServer();`;
}

async function runCli(...args: string[]) {
  if (!app) throw new Error("Fixture is not initialized.");
  return await runCommand({
    command: fixtureBin(app.cwd, "react-router-hono-server"),
    args,
    cwd: app.cwd,
  });
}

afterEach(async () => {
  await app?.stop();
  app = undefined;
});

test("installed CLI reveals a working file and infers Node by default", async () => {
  app = await ProductionFixture.create("basic", "node");
  await rm(path.join(app.cwd, "app/server.ts"));
  const result = await runCli("reveal", "file");

  expect(await readFile(path.join(app.cwd, "app/server.ts"), "utf8")).toBe(serverSource("node"));
  expect(result.stdout).toContain("File created at");

  await app.build();
  await app.startProduction();
  expect((await app.fetch("/")).status).toBe(200);
});

test("installed CLI reveals a folder and infers every explicit runtime", async () => {
  app = await ProductionFixture.create("basic", "node");
  const cases = [
    ["bun", "bun"],
    ["deno", "deno"],
    ["cloudflare", "cloudflare"],
    ["aws", "aws-lambda"],
  ] as const;

  for (const [runtime, adapter] of cases) {
    await app.edit(
      "vite.config.ts",
      `import { reactRouterHonoServer } from "react-router-hono-server/dev";\nreactRouterHonoServer({ runtime: "${runtime}" });\n`
    );
    await runCli("reveal", "folder");
    expect(await app.read("app/server/index.ts")).toBe(serverSource(adapter));
  }
});

test("installed React Router CLI reveals its rendering entries", async () => {
  app = await ProductionFixture.create("basic", "node");
  await rm(path.join(app.cwd, "app/entry.client.tsx"));
  await rm(path.join(app.cwd, "app/entry.server.tsx"));

  await runCommand({
    command: fixtureBin(app.cwd, "react-router"),
    args: ["reveal"],
    cwd: app.cwd,
  });

  expect(await app.read("app/entry.client.tsx")).toContain("hydrateRoot");
  expect(await app.read("app/entry.server.tsx")).toContain("renderToPipeableStream");
});
