import fs from "node:fs";
import path from "node:path";
import { command, run } from "@drizzle-team/brocli";

const serverFile = `// generated by react-router-hono-server/dev
import { createHonoServer } from "react-router-hono-server/node";
export default await createHonoServer();`;

const file = command({
  name: "file",
  async handler() {
    const serverFilePath = path.resolve(process.cwd(), "app", "server.ts");
    fs.writeFileSync(serverFilePath, serverFile);
  },
});

const folder = command({
  name: "folder",
  async handler() {
    const serverFilePath = path.resolve(process.cwd(), "app", "server", "index.ts");

    if (!fs.existsSync(serverFilePath)) {
      fs.mkdirSync(path.dirname(serverFilePath), { recursive: true });
    }

    fs.writeFileSync(serverFilePath, serverFile);
  },
});

const reveal = command({
  name: "reveal",
  subcommands: [file, folder],
});

run([reveal], {
  name: "React Router Hono Server CLI",
});
