import fs from "node:fs";
import path from "node:path";
import { command, run } from "@drizzle-team/brocli";

const runtimeRegex = /runtime:\s*(['"])([^'"]*)\1/;

function guessRuntime() {
  try {
    const viteConfig = fs.readFileSync(path.resolve(process.cwd(), "vite.config.ts"), "utf-8");
    return viteConfig.match(runtimeRegex)?.[2] || "node";
  } catch {
    return "node";
  }
}

const runtime = guessRuntime();

const serverFile = `// generated by react-router-hono-server/dev
import { createHonoServer } from "react-router-hono-server/${runtime}";

export default await createHonoServer();`;

const file = command({
  name: "file",
  handler() {
    const serverFilePath = path.resolve(process.cwd(), "app", "server.ts");

    fs.writeFileSync(serverFilePath, serverFile);

    console.log(`\x1b[33m✨ File created at ${serverFilePath}\x1b[0m`);
  },
});

const folder = command({
  name: "folder",
  handler() {
    const serverFilePath = path.resolve(process.cwd(), "app", "server", "index.ts");

    if (!fs.existsSync(serverFilePath)) {
      fs.mkdirSync(path.dirname(serverFilePath), { recursive: true });
    }

    fs.writeFileSync(serverFilePath, serverFile);

    console.log(`\x1b[33m✨ Folder and file created at ${serverFilePath}\x1b[0m`);
  },
});

const reveal = command({
  name: "reveal",
  subcommands: [file, folder],
});

run([reveal], {
  name: "React Router Hono Server CLI",
});
