import fs from "node:fs";
import type { IncomingMessage, ServerResponse } from "node:http";
import path from "node:path";
import { pathToFileURL } from "node:url";
import honoDevServer, { type DevServerOptions } from "@hono/vite-dev-server";
import bunAdapter from "@hono/vite-dev-server/bun";
import nodeAdapter from "@hono/vite-dev-server/node";
import type { Config as ReactRouterConfig } from "@react-router/dev/config";
import type { Plugin, UserConfig } from "vite";
import { isReactRouterBuildRequest } from "./react-router-build-request";
import type { Runtime } from "./types/runtime";

type MetaEnv<T> = {
  [K in keyof T as `import.meta.env.${string & K}`]: T[K];
};

type ReactRouterHonoServerPluginOptionsBase = {
  /**
   * The path to the server file, relative to `vite.config.ts`.
   *
   * If it is a folder (`app/server`), it will look for an `index.ts` file.
   *
   * Defaults to `${appDirectory}/server[.ts | /index.ts]` if present.
   *
   * Fallback to a virtual module `virtual:react-router-hono-server/server`.`
   */
  serverEntryPoint?: string;
  /**
   * The paths that are not served by the dev-server.
   *
   * Defaults include `appDirectory` content.
   */
  dev?: {
    /**
     * The paths that are not served by the dev-server.
     *
     * Defaults include `appDirectory` content.
     */
    exclude?: DevServerOptions["exclude"];
    /**
     * The name of the export to use for the server.
     *
     * Defaults to `default`.
     */
    export?: DevServerOptions["export"];
  };
};

type ReactRouterHonoServerPluginOptionsDefault = ReactRouterHonoServerPluginOptionsBase & {
  /**
   * The runtime to use for the server.
   *
   * Defaults to `node`.
   */
  runtime?: Runtime;
};

type ReactRouterHonoServerPluginOptions = ReactRouterHonoServerPluginOptionsDefault;

const REACT_ROUTER_SERVER_BUILD_MODULE_ID = "\0virtual:react-router/server-build";
const VIRTUAL_MODULE_ID = "\0virtual:react-router-hono-server/server";

export function reactRouterHonoServer(options: ReactRouterHonoServerPluginOptions = {}): Plugin {
  const runtime: Runtime = options.runtime || "node";
  const adapterEntryPoint = runtime === "aws" ? "aws-lambda" : runtime;
  let pluginConfig: PluginConfig;
  let devServerPlugin: Plugin | undefined;
  let previewAppPromise: Promise<{ fetch(request: Request): Response | Promise<Response> }> | undefined;

  return {
    name: "react-router-hono-server",
    enforce: "post",
    resolveId(id) {
      if (id === VIRTUAL_MODULE_ID) {
        return id;
      }
    },
    load(id) {
      if (id === VIRTUAL_MODULE_ID) {
        return `
          // generated by react-router-hono-server/dev
          import { createHonoServer } from "react-router-hono-server/${adapterEntryPoint}";

          export default await createHonoServer();
        `;
      }
    },
    configResolved(config) {
      if (
        runtime === "cloudflare" &&
        !config.plugins.some(
          (plugin) => plugin.name === "vite-plugin-cloudflare" || plugin.name.startsWith("vite-plugin-cloudflare:")
        )
      ) {
        throw new Error(
          'Missing cloudflare() in vite.config.ts. Add it with: import { cloudflare } from "@cloudflare/vite-plugin".'
        );
      }
    },
    config(config, env) {
      pluginConfig = resolvePluginConfig(config, options);

      if (!pluginConfig) {
        return;
      }

      const serverEntryPoint = pluginConfig.serverEntryPoint;
      const denoDevReactExternals = runtime === "deno" && env.mode === "development" ? ["react", "react-dom"] : [];

      const baseConfig = {
        // Define environment variables that are hot-swapped during development and SSR build
        define: {
          "import.meta.env.REACT_ROUTER_HONO_SERVER_BUILD_DIRECTORY": JSON.stringify(pluginConfig.buildDirectory),
          "import.meta.env.REACT_ROUTER_HONO_SERVER_ASSETS_DIR": JSON.stringify(pluginConfig.assetsDir),
          "import.meta.env.REACT_ROUTER_HONO_SERVER_RUNTIME": JSON.stringify(runtime),
          "import.meta.env.REACT_ROUTER_HONO_SERVER_BASENAME": JSON.stringify(pluginConfig.basename),
        } satisfies MetaEnv<ReactRouterHonoServerEnv>,
        ssr: {
          target: runtime === "cloudflare" ? "webworker" : undefined,
          // Ensure our package is not externalized during SSR build
          // This is necessary because we are using a virtual import to load the React Router server entry point
          noExternal: ["react-router-hono-server"],
          // Vite's ESM SSR runner cannot evaluate CJS `react-dom/server.*` (`require is not defined`).
          // In Deno dev, let Deno's npm loader handle React instead of inlining those files.
          ...(runtime === "cloudflare" ? {} : { external: [...denoDevReactExternals] }),
          optimizeDeps: runtime === "bun" ? { include: ["react-dom/server"], exclude: ["react"] } : undefined,
        },
      } satisfies UserConfig;

      let reactRouterBuildFile = pluginConfig.serverBuildFile;

      if (reactRouterBuildFile === "index.js") {
        reactRouterBuildFile = "assets/server-build.js";
      }

      const resolve: UserConfig["resolve"] = {};

      if (runtime === "cloudflare") {
        resolve.alias = {
          "react-dom/server": "react-dom/server.edge",
        };
      }

      if (runtime === "bun") {
        // React's Bun-specific direct stream closes when a suspended render yields.
        // Keep React Router's Web Streams entry unchanged and select the standard renderer.
        resolve.alias = {
          "react-dom/server": "react-dom/server.browser",
        };
      }

      if (runtime === "deno" && env.mode !== "development") {
        // Official react-dom `deno` condition. Do not apply this alias in Vite
        // dev: it forces a CJS file path that Vite's ESM runner evaluates with
        // `require`, which Deno does not provide.
        resolve.alias = {
          "react-dom/server": "react-dom/server.browser",
        };
      }

      const ssrConfig = {
        resolve: {
          ...resolve,
          ...(denoDevReactExternals.length > 0
            ? {
                external: denoDevReactExternals,
              }
            : {}),
        },
        build: {
          rollupOptions: {
            ...(runtime === "cloudflare" ? {} : { input: serverEntryPoint }),
            output: {
              entryFileNames: (chunk) => {
                // https://github.com/remix-run/react-router/issues/13226#issuecomment-2773364665
                // RR expects to find its virtual module id in build/server/.vite/manifest.json in order to prerender
                // This is hacky but it's the only thing that works
                chunk.facadeModuleId = REACT_ROUTER_SERVER_BUILD_MODULE_ID;

                return "index.js";
              },
              // not invoked when target is webworker (single file output)
              chunkFileNames: (chunk) => {
                if (chunk.name === "server-build") {
                  return reactRouterBuildFile;
                }

                return "assets/[name]-[hash].js";
              },
              manualChunks:
                runtime !== "cloudflare"
                  ? (id, meta) => {
                      // Make modules that are imported by the server entry point a chunk
                      if (meta.getModuleInfo(id)?.importers.some((id) => id.includes(serverEntryPoint))) {
                        return path.basename(id, path.extname(id));
                      }

                      return undefined;
                    }
                  : undefined,
            },
          },
        },
      } satisfies Omit<UserConfig, "plugins">;

      return {
        ...baseConfig,
        resolve,
        environments: {
          ssr: ssrConfig as any,
        },
      };
    },
    configureServer(server) {
      // bind viteDevServer to global 🤫
      globalThis.__viteDevServer = server;

      if (!pluginConfig) {
        return;
      }

      // The official Cloudflare Vite plugin owns the Workerd-backed dev
      // environment and loads the Wrangler main entry. Installing Hono's Node
      // dev middleware as well would route requests through a non-runnable Vite
      // environment and prevent Vite client modules from reaching the browser.
      if (runtime === "cloudflare") {
        return;
      }

      if (devServerPlugin) {
        return;
      }

      let adapter: DevServerOptions["adapter"] = nodeAdapter;

      if (runtime === "bun") {
        adapter = bunAdapter;
      }

      if (runtime === "deno") {
        adapter = () => {
          if (typeof globalThis.navigator === "undefined") {
            // @ts-expect-error not typed well
            globalThis.navigator = {
              userAgent: "Deno",
            };
          } else {
            Object.defineProperty(globalThis.navigator, "userAgent", {
              value: "Deno",
              writable: false,
            });
          }
          return {
            env: Deno.env.toObject(),
          };
        };
      }

      // Create and apply the Hono dev server plugin
      devServerPlugin = honoDevServer({
        adapter,
        injectClientScript: false,
        entry: pluginConfig.serverEntryPoint,
        export: options.dev?.export || "default",
        exclude: [
          new RegExp(
            `^(?=\\/${pluginConfig.appDirectory.replace(/^[/\\]+|[/\\]+$/g, "").replaceAll(/[/\\]+/g, "/")}\\/)((?!.*\\.data(\\?|$)).*\\..*(\\?.*)?$)`
          ),
          new RegExp(
            `^(?=\\/${
              pluginConfig.appDirectory
                .replace(/^[/\\]+|[/\\]+$/g, "")
                .replaceAll(/[/\\]+/g, "/")
                .split("/")[0]
            }\\/)((?!.*\\.data(\\?|$)).*\\..*(\\?.*)?$)`
          ),
          /\?import(\?.*)?$/,
          /^\/@.+$/,
          /^\/node_modules\/.*/,
          `^(?=\\/${pluginConfig.appDirectory.replace(/^[/\\]+|[/\\]+$/g, "").replace(/[/\\]+/g, "/")}/**/.*/**)`,
          `^(?=\\/${
            pluginConfig.appDirectory
              .replace(/^[/\\]+|[/\\]+$/g, "")
              .replace(/[/\\]+/g, "/")
              .split("/")[0]
          }/**/.*/**)`,
          ...(pluginConfig.dev?.exclude || []),
        ],
      });

      // Bind socket info to the request headers
      server.middlewares.use((req: IncomingMessage, _res: ServerResponse, next: () => void) => {
        req.rawHeaders.push("x-remote-address", req.socket.remoteAddress || "unknown");
        req.rawHeaders.push("x-remote-port", String(req.socket.remotePort || "unknown"));
        req.rawHeaders.push("x-remote-family", req.socket.remoteFamily || "unknown");

        next();
      });

      // Apply the dev server plugin's configureServer hook if it exists
      if (typeof devServerPlugin.configureServer === "function") {
        // @ts-expect-error - FIXME: Come back to this later
        devServerPlugin.configureServer(server);
      } else {
        console.error("Dev server plugin configureServer hook is not a function. This is likely a bug, I guess 😅\n");
        throw new Error("Cannot apply dev server plugin configureServer hook");
      }
    },
    configurePreviewServer(server) {
      server.middlewares.use(async (req, res, next) => {
        if (runtime === "cloudflare" || !isReactRouterBuildRequest() || !pluginConfig) {
          next();
          return;
        }

        try {
          previewAppPromise ??= import(
            pathToFileURL(path.resolve(pluginConfig.rootDirectory, pluginConfig.buildDirectory, "server/index.js")).href
          ).then((module) => module.default);
          const app = await previewAppPromise;
          const headers = new Headers();
          for (const [name, value] of Object.entries(req.headers)) {
            for (const item of Array.isArray(value) ? value : [value]) {
              if (item !== undefined) headers.append(name, item);
            }
          }
          const request = new Request(`http://${req.headers.host ?? "localhost"}${req.url ?? "/"}`, {
            method: req.method,
            headers,
          });
          const response = await app.fetch(request);

          res.statusCode = response.status;
          response.headers.forEach((value, name) => {
            res.setHeader(name, value);
          });
          res.end(Buffer.from(await response.arrayBuffer()));
        } catch (error) {
          console.error(error);
          next(error);
        }
      });
    },
  };
}

type ReactRouterPluginContext = {
  reactRouterConfig: Required<ReactRouterConfig>;
  environmentBuildContext: { name: "client" | "ssr" } | null;
  rootDirectory: string;
  entryClientFilePath: string;
  entryServerFilePath: string;
};

function resolvePluginConfig(config: UserConfig, options: ReactRouterHonoServerPluginOptions) {
  if (!("__reactRouterPluginContext" in config)) {
    return null;
  }

  const { reactRouterConfig, environmentBuildContext, rootDirectory } =
    config.__reactRouterPluginContext as ReactRouterPluginContext;
  const buildDirectory = path.relative(rootDirectory, reactRouterConfig.buildDirectory);
  const appDirectory = path.relative(rootDirectory, reactRouterConfig.appDirectory);
  const isSsrBuild = environmentBuildContext?.name === "ssr";
  const assetsDir = config.build?.assetsDir || "assets";
  const serverEntryPoint = options.serverEntryPoint || findDefaultServerEntry(appDirectory);
  const serverBuildFile = reactRouterConfig.serverBuildFile;
  const basename = reactRouterConfig.basename;

  return {
    rootDirectory,
    buildDirectory,
    appDirectory,
    isSsrBuild,
    assetsDir,
    serverEntryPoint,
    dev: options.dev,
    serverBuildFile,
    basename,
  };
}

type PluginConfig = ReturnType<typeof resolvePluginConfig>;

let warned = false;

function findDefaultServerEntry(appDirectory: string): string {
  const fileWay = `${appDirectory}/server.ts`;
  const folderWay = `${appDirectory}/server/index.ts`;

  // Check if direct file exists
  if (fs.existsSync(fileWay)) {
    return fileWay;
  }

  // Check if index file exists
  if (fs.existsSync(folderWay)) {
    return folderWay;
  }

  if (!warned) {
    console.warn(
      `\x1b[33mNo server entry point found.\nWill use a virtual module (${VIRTUAL_MODULE_ID}) with a default Hono server.\n\nTo customize the server, create one of the following files:\n - ${fileWay} (npx react-router-hono-server reveal file)\n - ${folderWay} (npx react-router-hono-server reveal folder)\nYou can also set the \`serverEntryPoint\` option in the reactRouterHonoServer plugin for more control.\x1b[0m\n`
    );
    warned = true;
  }
  // If neither create a virtual module with a default Hono server
  return VIRTUAL_MODULE_ID;
}
